version: "3.8"

services:
  # celery:
  #   image: celery_task
  #   build: .
  #   command: celery -A celery worker -Q celery -c 1 -P prefork --loglevel=info
  #   environment: 
  #     - C_FORCE_ROOT=true
  #   depends_on:
  #     - guane_inter 
  #     - rabbitmq 
  #     - redis 
  
  guane_inter:
    image: guane_intern_api
    build: ./
    environment: 
      - DB_URL=postgres://postgres:postgres@postgres:5432/guane_intern_db
   
    depends_on:
      - postgres 
    ports: 
      - "8001:8000"
    networks:
      network-cano:
        aliases:
          - guane_intern_api
    volumes:
      - ./:/usr/src/app/            

  postgres:
    image: guane_db
    build: 
      context: ./DB
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      network-cano:
        aliases:
          - guane_db
    volumes:
      - volume_cano:/var/lib/postgresql/data
    
  
  # rabbitmq:
  #   image: rabbitmq:3-management
  #   ports:
  #    - 5671:5671
  #    - 5672:5672
  #    - 15671:15671
  #    - 15672:15672
    
  # redis:
  #   image: redis:latest
  #   ports:
  #     - "6379:6379"    

volumes:
  volume_cano:
    external: true 


networks:
  network-cano:
    external: true